apiVersion: v1
kind: Service
metadata:
  name: shield
  namespace: shield
spec:
  type: NodePort
  selector:
    app: shield
    department: it
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9000