apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shield-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shield-deployment
  namespace: shield-apps
spec:
  selector:
    matchLabels:
      app: shield
      department: it
  replicas: 1
  template:
    metadata:
      labels:
        app: shield
        department: it
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shield-pvc
      containers:
      - name: shield
        image: "sonarqube:latest"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "800Mi"
            cpu: "900m"
        env:
          - name: "SONARQUBE_JDBC_USERNAME"
            value: "db-user-name"
          - name: "SONARQUBE_JDBC_URL"
            value: "jdbc:postgresql://private-ip-of-postgres-db:5432/db-name" # DB Private IP Values can be fecthed in the output section of Terraform Postgresql Script.
          - name: "SONARQUBE_JDBC_PASSWORD"
            value: "sonarqubedbpassword"
        volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: data
        ports:
          - containerPort: 9000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shield-pvc
  namespace: shield-apps
  annotations: 
    volume.beta.kubernetes.io/storageclass: shield-ssd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
